version: '3.1'

services:

  order-db:
    image: debezium/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: migration
    ports:
      - 10001:5432
